services:
  - type: web
    name: chabalgo-api
    runtime: python
    plan: free
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FRED_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.11"
