"use client";

import { useState } from "react";

const DEFINITIONS: Record<string, { title: string; desc: string }> = {
  pe: {
    title: "PE Ratio (Trailing)",
    desc: "Price-to-Earnings: stock price ÷ earnings per share over the last 12 months. Lower = cheaper relative to past earnings. S&P 500 average is ~20x.",
  },
  forward_pe: {
    title: "Forward PE",
    desc: "Same idea but uses analyst-projected earnings for the next 12 months. If lower than trailing PE, the market expects earnings growth.",
  },
  revenue_growth: {
    title: "Revenue Growth YoY",
    desc: "How much sales grew vs the same quarter last year. >20% = hyper-growth. <0% = declining business.",
  },
  gross_margin: {
    title: "Gross Margin",
    desc: "Profit after cost of goods sold, as % of revenue. >60% suggests strong pricing power. <30% is a thin-margin business.",
  },
  operating_margin: {
    title: "Operating Margin",
    desc: "Profit after all operating costs (R&D, marketing, salaries) as % of revenue. Best proxy for business efficiency.",
  },
  eps: {
    title: "EPS",
    desc: "Earnings Per Share. Net income divided by shares outstanding. Negative EPS = unprofitable.",
  },
  net_debt: {
    title: "Net Debt",
    desc: "Total debt minus cash & equivalents. Negative = more cash than debt (very strong balance sheet).",
  },
  rsi: {
    title: "RSI (Relative Strength Index)",
    desc: "Momentum oscillator from 0-100. >70 = overbought (might pullback). <30 = oversold (might bounce). 50 = neutral.",
  },
  ma50: {
    title: "MA50",
    desc: "50-day moving average. Price above MA50 = short-term uptrend. Below = downtrend.",
  },
  ma200: {
    title: "MA200",
    desc: "200-day moving average. The 'investor's line.' Above = long-term bull regime. Below = bear regime.",
  },
  beta: {
    title: "Beta",
    desc: "Volatility relative to S&P 500. Beta of 1 = moves with market. >1.5 = amplified moves. <1 = defensive.",
  },
  fwd_pe: {
    title: "Forward PE",
    desc: "Same as Forward PE — analyst-projected earnings.",
  },
  market_cap: {
    title: "Market Capitalization",
    desc: "Share price × shares outstanding. Total value of the company. >$200B = mega-cap, $10-200B = large, $2-10B = mid, <$2B = small.",
  },
  fcf: {
    title: "Free Cash Flow",
    desc: "Cash generated by operations minus capital expenditures. The most honest profit metric — harder to manipulate than EPS.",
  },
  dividend_yield: {
    title: "Dividend Yield",
    desc: "Annual dividend ÷ share price. Higher = more income, but very high yields (>6%) often signal distressed stock.",
  },
  short_interest: {
    title: "Short Interest",
    desc: "% of float being shorted by traders betting on a decline. >10% = lots of bearish bets. >25% = squeeze potential.",
  },
};

interface MetricTooltipProps {
  metric: keyof typeof DEFINITIONS | string;
  children: React.ReactNode;
}

export default function MetricTooltip({ metric, children }: MetricTooltipProps) {
  const [show, setShow] = useState(false);
  const def = DEFINITIONS[metric.toLowerCase()];

  if (!def) return <>{children}</>;

  return (
    <span
      className="relative inline-flex items-center gap-1 cursor-help"
      onMouseEnter={() => setShow(true)}
      onMouseLeave={() => setShow(false)}
    >
      {children}
      <svg className="w-3 h-3 text-muted/40 hover:text-accent transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      {show && (
        <span className="absolute bottom-full left-0 mb-2 z-50 w-72 p-3 bg-card border border-border rounded-xl shadow-2xl shadow-black/30 pointer-events-none">
          <span className="block text-xs font-bold text-accent mb-1">{def.title}</span>
          <span className="block text-[11px] text-muted leading-relaxed">{def.desc}</span>
        </span>
      )}
    </span>
  );
}
